### ISSUE TITLE
Unable to sign client certificate

### ISSUE THREAD

**Issue by rokkhan** [inverse-inc/packetfence-pki#5]
Hi, 
I have fresh installation of packetfence 6.2.1 and packetfence-pki on Centos 6.
I have created a client certificate but when I click on "Sign" icon of the certificate I get this error:

Environment:

Request Method: GET
Request URL: https://slx00012040:9393/pki/cert/2/sign/

Django Version: 1.6.11
Python Version: 2.6.6
Installed Applications:
('django.contrib.admin',
 'django.contrib.auth',
 'django.contrib.contenttypes',
 'django.contrib.sessions',
 'django.contrib.messages',
 'django.contrib.staticfiles',
 'rest_framework',
 'rest_framework.authtoken',
 'bootstrap3',
 'pki')
Installed Middleware:
('django.contrib.sessions.middleware.SessionMiddleware',
 'django.middleware.common.CommonMiddleware',
 'django.middleware.csrf.CsrfViewMiddleware',
 'django.contrib.auth.middleware.AuthenticationMiddleware',
 'django.contrib.messages.middleware.MessageMiddleware',
 'django.middleware.clickjacking.XFrameOptionsMiddleware',
 'inverse.middleware.SecurityMiddleware')

Traceback:
File "/usr/lib/python2.6/site-packages/django/core/handlers/base.py" in get_response
1.                     response = wrapped_callback(request, _callback_args, *_callback_kwargs)
   File "/usr/lib/python2.6/site-packages/django/contrib/auth/decorators.py" in _wrapped_view
2.                 return view_func(request, _args, *_kwargs)
   File "/usr/local/packetfence-pki/pki/views.py" in sign_cert
3.         p.sign()
   File "/usr/local/packetfence-pki/pki/models.py" in sign
4.             x509.add_extensions([crypto.X509Extension("extendedKeyUsage", True, str(self.profile.extended_key_usage))])
   File "/usr/lib/python2.6/site-packages/OpenSSL/crypto.py" in **init**
5.             _raise_current_error()
   File "/usr/lib/python2.6/site-packages/OpenSSL/_util.py" in exception_from_error_queue
6.     raise exceptionType(errors)

Exception Type: Error at /pki/cert/2/sign/
Exception Value: [('asn1 encoding routines', 'a2d_ASN1_OBJECT', 'first num too large'), ('X509 V3 routines', 'V2I_EXTENDED_KEY_USAGE', 'invalid object identifier'), ('X509 V3 routines', 'X509V3_EXT_nconf', 'error in extension')]

**Comment by whitx** [comment]
Can you send a screenshot of your profile configuration? (in packetfence-pki)
It seems that an attribute in extended key usage is not written properly

**Comment by rokkhan** [comment]
![certificate](https://cloud.githubusercontent.com/assets/22644111/19131708/c9afc96c-8b50-11e6-97b9-c4b2f3b99dbe.jpg)

This one?

**Comment by fdurand** [comment]
A typo in Extended key usage !

**Comment by rokkhan** [comment]
Thanks!

There is a typo in the doc I just did a copy and paste from this guide and did not realise.

https://packetfence.org/doc/PacketFence_PKI_Quick_Install_Guide.html

So the correct one should be clientAuth ?

**Comment by fdurand** [comment]
yes for user certificates.
Btw we will fix the doc.
