### ISSUE TITLE
packetefence-pki fails signing user certificates

### ISSUE THREAD

**Issue by rokkhan** [inverse-inc/packetfence-pki#6]
Hi,

I´m trying to use packetenfe-pki to generate user certificates but I am unable.

Users are authenticated using an externa ldap source and moved to the android provisioning module where is shown the password will be used to export the certificate.

I click on "generate certificate" and I get a "Problem while preparing the TLS profile".
If I go to packetfence-pki certificate list I see that the certificate has been generated but has not been signed.

If click on sign icon I get the error I attach. 

If I try several times finally i get the certificate signed but this is not useful. What can I do?

My servers is a Centos 6.8, packetfence 6.5.1 and packefence-pki 1.0.4

Thanks in advance,

[pki.txt](https://github.com/inverse-inc/packetfence-pki/files/1222486/pki.txt)

**Comment by whitx** [comment]
Could you try to update the pki?
The actual version is 1.0.5-3.1, some bugfixes have been made in the past few versions.
I will have a look at your log also.

Thanks

**Comment by rokkhan** [comment]
Hi,

Do i have to update manually? I am using centos repo and it looks like there is no update for packetfence-pki

yum check-update --enablerepo=packetfence-extra | grep packetfence
perl-DateTime-Format-MySQL.noarch      0.05-2.2                       packetfence-extra
perl-Net-LDAP.noarch                   1:0.65-6.2                     packetfence-extra

What do I have to do? Sorry but I am quite newbie with packetfence.

Greetings.

**Comment by whitx** [comment]
enable both packetfence and packetfence-extra repo while doing so.

**Comment by rokkhan** [comment]
yum info packetfence-pki --enablerepo=packetfence,packetfence-extra
Complementos cargados:fastestmirror, security
Loading mirror speeds from cached hostfile
 * base: mirror.airenetworks.es
 * centosplus: mirror.airenetworks.es
 * epel: mirror.airenetworks.es
 * extras: mirror.airenetworks.es
 * updates: mirror.airenetworks.es
Paquetes instalados
Nombre        : packetfence-pki
Arquitectura        : noarch
Versión     : 1.0.4
Lanzamiento     : 1.el6
Tamaño        : 1.3 M
Repositorio        : installed
Desde el repositorio   : packetfence-extra
Resumen     : packetfence-pki
URL         : https://github.com/inverse-inc/packetfence-pki
Licencia     : GPL
Descripción :Small PKI to integrate with PacketFence for certificates generation when using EAP-TLS

**Comment by whitx** [comment]
My mistake the new version is only for centos7 not centos 6.
@fdurand any leads?

**Comment by rokkhan** [comment]
I am using default sqlite as database but I have seen than mysql could be also used a database, do you think this change could solve the issue?

**Comment by whitx** [comment]
The package is not updated anymore for CentOS6. There is no plan to do so either since our main distribution are now CentOS7 and Debian8. I would advise you to run the PKI on one of those oses, it can be on the server by itself without PacketFence and should work fine. You will not need a machine with a lot of ressources since the PKI is very light weight.
I can tell you that this problem is not present on the version running on CentOS7 or Debian8.

**Comment by rokkhan** [comment]
OMG, I did install on Centos 6 because packetenfe-pki was not able for Centos 7 about a year ago. The server has been working very good for guests users and now I wanted to use for BYOD with the pki, I was not planing to move to centos 7.
Could I only install the fix made in the new version on my centos 6? Is there a big change that does not allow to install this version on centos 6? Even manually?

**Comment by whitx** [comment]
You can try, but the issue is mainly coming from packages, we took some newer versions of package we are using for CentOS7, (pyOpenSSL for instance which the package causing your issue). I wish you good luck if you wan to try do so, but tbh getting a CentOS7 up and running with only the PKI is done in less than 30minutes.

**Comment by whitx** [comment]
Also if you ever plan to move on PacketFence 7+, you will need a CentOS7/Debian8 anyways :)

**Comment by rokkhan** [comment]
I had a lot of problems with previous versions of packetfence and all started to work very stable since version 6.3.0. So I was not thinking to upgrade to 7, but in this case maybe I should have to start testing centos 7 with pf7 in another server. Thanks for all!

**Comment by whitx** [comment]
You are welcome. As I said you could always just run the PKI on a separate server so you do not have to update your PF instance for now.
