### ISSUE TITLE
Unable to install packetfence-pki on packetefence-zen 7.1

### ISSUE THREAD

**Issue by rokkhan** [inverse-inc/packetfence-pki#7]
Hi,

I have installed packetfence 7.1 to solve the issue in this case: https://github.com/inverse-inc/packetfence-pki/issues/6

I have used the OVA file with packtefence 7.1 but when I try to install the package I get this error:

yum install packetfence-pki --enablerepo=packetfence-extra, packetfence
Loaded plugins: fastestmirror
Loading mirror speeds from cached hostfile
 * base: centos.mirror.ca.planethoster.net
 * extras: centos.bhs.mirrors.ovh.net
 * updates: ca.mirror.babylon.network
Resolving Dependencies
--> Running transaction check
---> Package packetfence-pki.noarch 0:1.0.5-3.1 will be installed
--> Processing Dependency: python-pyasn1-modules >= 0.1.7 for package: packetfence-pki-1.0.5-3.1.noarch
--> Processing Dependency: python-ldap for package: packetfence-pki-1.0.5-3.1.noarch
--> Processing Dependency: django-countries for package: packetfence-pki-1.0.5-3.1.noarch
--> Processing Dependency: python-django-rest-framework for package: packetfence-pki-1.0.5-3.1.noarch
--> Processing Dependency: python-django-bootstrap3 for package: packetfence-pki-1.0.5-3.1.noarch
--> Running transaction check
---> Package packetfence-pki.noarch 0:1.0.5-3.1 will be installed
--> Processing Dependency: django-countries for package: packetfence-pki-1.0.5-3.1.noarch
--> Processing Dependency: python-django-rest-framework for package: packetfence-pki-1.0.5-3.1.noarch
--> Processing Dependency: python-django-bootstrap3 for package: packetfence-pki-1.0.5-3.1.noarch
---> Package python-ldap.x86_64 0:2.4.15-2.el7 will be installed
---> Package python2-pyasn1-modules.noarch 0:0.1.9-7.el7 will be installed
--> Finished Dependency Resolution
Error: Package: packetfence-pki-1.0.5-3.1.noarch (packetfence-extra)
           Requires: python-django-bootstrap3
Error: Package: packetfence-pki-1.0.5-3.1.noarch (packetfence-extra)
           Requires: python-django-rest-framework
Error: Package: packetfence-pki-1.0.5-3.1.noarch (packetfence-extra)
           Requires: django-countries
 You could try using --skip-broken to work around the problem
 You could try running: rpm -Va --nofiles --nodigest

What am i doing wrong?

**Comment by fdurand** [comment]
I will push a new rpm soon

**Comment by fdurand** [comment]
I have just uploaded a new rpm in the repo.
Can you do that:
yum makecache --enablerepo=packetfence,packetfence-extra
yum install packetfence-pki --enablerepo=packetfence-extra, packetfence

**Comment by rokkhan** [comment]
Hi Fabrice,

I did the update to pf 7.2 and after installed packetence-pki and it
worked. Thanks a lot,

Greetings.

2017-08-26 14:17 GMT+02:00 Durand <notifications@github.com>:

**Comment by thejimmahknows** [comment]
I am receiving this same error with ZEN v7.3 regarding **python-django-bootstrap3** and **python-django-rest-framework**. Is the packetgence-pki not compatibility with ZEN v7.3?
